Personal_project_bookmake/accounts/urls.py
from django.urls import pathfrom django.contrib.auth.views import LoginView,LogoutViewfrom .views import UserList, signupapp_name = "accounts"urlpatterns = [    path('user/list/', UserList.as_view(), name = 'user_list'),    path('login/',LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),    path('logout/',LogoutView.as_view(template_name = 'accounts/logout.html'), name = 'logout'),    path('signup/',signup,name='signup'),]

Personal_project_bookmake/bookmake/urls.py
from django.urls import pathfrom .views import *app_name = 'bookmake'urlpatterns = [    path('',BookmakeList.as_view(), name = 'index'),    path('update/<int:pk>/', BookmakeUpdate.as_view(), name='update'),    path('delete/<int:pk>/', BookmakeDelte.as_view(), name='delete'),]

Personal_project_bookmake/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin_tsh/', admin.site.urls),
    path('',include('bookmake.urls')),
    path('accounts/',include('accounts.urls'))
]

Personal_project_bookmake/accounts/models.py
from django.db import models

from django.contrib.auth.models import User

class Follow(models.Model):

    me = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    you = models.ForeignKey(User, on_delete=models.CASCADE,related_name='follower')

    def __str__(self):
        return self.me.username+" follow "+self.you.username

Personal_project_bookmake/bookmake/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Bookmake(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    site_name = models.CharField(max_length=50)
    url = models.URLField('Site URL')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.site_name + " : " + self.url

    class Meta:
        ordering = ['-site_name']

Personal_project_bookmake/accounts/forms.py
from django.contrib.auth.models import Userfrom django import formsclass SignUpForm(forms.ModelForm):    password = forms.CharField(label='Password', widget=forms.PasswordInput)    Response_password = forms.CharField(label='Res_password', widget = forms.PasswordInput)    class Meta:        model = User        fields = ['username', 'password', 'Response_password', 'first_name', 'last_name', 'email']    def clean_Response_password(self):        cd = self.cleaned_data        if cd['password'] != cd['Response_password']:            raise forms.ValidationError('비밀번호가 일치하지 않습니다.')        return cd['Response_password']

Personal_project_bookmake/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic.list import ListView


class UserList(ListView):
    User = get_user_model()
    template_name = 'accounts/user_list.html'

from .forms import SignUpForm
def signup(request):
    if request.method == "POST":
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user_instance = signup_form.save(commit = False)
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()

            return render(request, 'accounts/signup_complete.html', {'username':user_instance.username})
    else:
        signup_form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form':signup_form})

Personal_project_bookmake/bookmake/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from .models import Bookmake
from django.views.generic.edit import UpdateView,DeleteView,CreateView

class BookmakeList(ListView):
    model = Bookmake
    template_name_suffix = '_list'

class BookmakeUpdate(UpdateView):
    model = Bookmake
    template_name_suffix = '_update'
    fields = ['site_name', 'url']
    success_url = '/'

class BookmakeDelte(DeleteView):
    model = Bookmake
    template_name_suffix = '_delete'
    fields = ['site_name', 'url']

Personal_project_bookmake/accounts/templates/accounts/login.html
{% extends 'base.html' %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        {% if user.is_active %}            <h2> Welcome, {{user.username}} </h2>            <a href="{% url 'accounts:logout' %}">로그아웃</a>        {% else %}        {% if form.errors %}            <p>ID나 비밀번호가 일치하지 않습니다.</p>        {% endif %}        <form method="post" action="{% url 'accounts:login' %}">        {% csrf_token %}        {{ form.as_p }}        <input type="submit" value="Login" class="btn btn-outline-primary">        </form>    </div>    <div class="col"></div></div>{% endif %}{% endblock %}

Personal_project_bookmake/accounts/templates/accounts/logout.html
{% extends 'base.html' %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <div class="alert alert-primary">정말로 로그아웃 하시겠습니까?</div>        <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">Login</a>        <a href="{% url 'bookmake:index' %}" class="btn btn-outline-secondary">Home</a>    </div>    <div class="col"></div></div>{% endblock %}

Personal_project_bookmake/accounts/templates/accounts/signup.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <form action="" method="post">            <div class="alert alert-info">Please enter your account information</div>            {% csrf_token %}            {{ form.as_p }}            <input type="submit" value="Sign Up" class="btn btn-outline-info">        </form>    </div>    <div class="col"></div></div>{% endblock %}

Personal_project_bookmake/accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <div class="alert alert-success">{{username}} successfully signed up.</div>        <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">Move to Sign in</a>    </div>    <div class="col"></div></div>{% endblock %}

Personal_project_bookmake/accounts/templates/accounts/user_list.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <table class="table">            <tbody>            {% for object in object_list %}                <tr>                    <td>{{object.username}}</td>                    <td>{{object.firstname}} {{object.lastname}}</td>                </tr>            </tbody>        </table>    </div>    <div class="col"></div></div>{% endblock %}

Personal_project_bookmake/bookmake/templates/bookmake/bookmake_delete.html
{% extends 'base.html' %}{% block content %}{% endblock %}

Personal_project_bookmake/bookmake/templates/bookmake/bookmake_list.html
{% extends 'base.html' %}{% block content %}{% if user.is_authenticated %}    <table class="table">        <thead>        <tr>            <th>#</th>            <th>Site Name</th>            <th>URL</th>            <th>Delete</th>        </tr>        </thead>        <tbody>            {% for object in object_list %}            <tr>                <td>{{object.id}}</td>                <td>{{object.site_name}}</td>                <td>                    <a href="{{object.url}}" target="_blank">{{object.url}}</a><br>                    작성자 : {{object.author}}                </td>            {% endfor %}        </tbody>    </table>{% else %}    <table class="table_logout">        <tr>로그인 후 이용가능한 페이지입니다.</tr>    </table>{% endif %}{% endblock %}

Personal_project_bookmake/bookmake/templates/bookmake/bookmake_update.html
{% extends 'base.html' %}{% block content %}{% endblock %}