dstargram_project/accounts/urls.py
from django.urls import pathfrom django.contrib.auth.views import LoginView, LogoutViewapp_name = 'accounts'urlpatterns = [    path('signin/', LoginView.as_view(template_name = 'accounts/signin.html'), name ='signin'),    path('signout/', LogoutView.as_view(template_name = 'accounts/signout.html'), name='signout'),]

dstargram_project/accounts/models.py
from django.db import models

# Create your models here.

dstargram_project/accounts/views.py
from django.shortcuts import render

# Create your views here.

dstargram_project/accounts/templates/accounts/signin.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <div class="alert alert-primary">Please enter your login information.</div>        <form action="" method="post">            {% csrf_token %}            {{form.as_p}}            <input type="submit" value="Signin" class="btn btn-outline-primary">        </form>    </div>    <div class="col"></div></div>{% endblock %}

dstargram_project/accounts/templates/accounts/signout.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <div class="alert alert-primary">You successfully sign out.</div>        <a href="{% url 'accounts:signin' %}" class="btn btn-outline-success">Sign In</a>    </div>    <div class="col"></div></div>{% endblock %}