dstargram_project/photo/urls.py
from django.urls import pathfrom .views import *app_name = 'photo'urlpatterns = [    path('create/', PhotoCreate.as_view(), name='create'),    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),    path('', PhotoList.as_view(), name='index'),]

dstargram_project/photo/models.py
from django.db import models

# Create your models here.
# 기본 모델
"""

작성자 : author
본문 : text
사진 : image
작성일 : created
수정일 : updated
+ tag, like
-- comment
"""
from django.contrib.auth.models import User
from django.urls import reverse
# url pattern 이름을 가지고 주소를 만들어주는 함수

# User모델은 확장 가능
# settings.AUTH_USER_MODEL
# from django.contrib.auth import get_user_model
class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='photos')# (연결되는 모델, 삭제시 동작, 연관이름)
    # related_name 으로 연관 데이터를 얻을 수 없다면 쿼리를 별도로 실행해야 한다.
    # 내 프로필 페이지 - 내가 올린 사진만 뜬다.

    # models.Foreignkey(get_user_model(),)
    # CASCADE 연속해서 지운다. 탈퇴하면 사진도 싹 지운다.
    # PROTECT 사진 다 안지우면 너 탈퇴 안됨!! - 탈퇴 프로세스에 사진을 우선 삭제하고 탈퇴 시킨다.
    # 특정값으로 셋팅 -

    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d') # Ymd 경로 자동 생성
    # upload_to는 함수를 사용해서 폴더를 동적으로 설정할 수 있다.
    created = models.DateTimeField(auto_now_add=True) # 시간 생성
    updated = models.DateTimeField(auto_now=True) # 수정일로 할때
    # def __str__(self):
    #     return self.author

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        # detail/<int:pk>/
        return reverse('photo:detail', args=[self.id])

dstargram_project/photo/views.py
from django.shortcuts import render

# Create your views here.
# CRUDL - 이미지를 띄우는 방법
# 제네릭 뷰
# 쿼리셋 변경하기, context_data 추가하기, 권한체크
# 함수형 <-> 클래스형 뷰

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Photo

class PhotoList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

from django.shortcuts import redirect
class PhotoCreate(CreateView):
    model = Photo
    fields = ['author', 'image', 'text']
    template_name = 'photo/photo_create.html'
    #success_url = '/'

    def form_valid(self, form):
        # 입력된 자료가 올바른지 체크
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 올바르다면
            # form : 모델 폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면
            return self.render_to_response({'form':form})

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['image', 'text']
    template_name = 'photo/photo_update.html'
    #success_url = '/'

class PhotoDelete(DeleteView):
    model = Photo
    #fields = ['image', 'text']
    template_name = 'photo/photo_delete.html'
    #success_url = '/'

class PhotoDetail(DetailView):
    model = Photo
    template_name = 'photo/photo_detail.html'

dstargram_project/photo/templates/photo/photo_create.html
{% extends 'base.html' %}{% block title %}Photo Create{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <form action="" method="post" enctype="multipart/form-data">            <div class="alert alert-info">Please enter your photo information,</div>                {% csrf_token %}                {{form.as_p}}            <input type="submit" value="Create" class="btn btn-outline-primary"></input>        </form>    </div>    <div class="col"></div></div>{% endblock %}

dstargram_project/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}{% block title %}Photo Delete{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <form action="" method="post">            <div class="alert alert-danger">Do you want to delete {{object}}?</div>                {% csrf_token %}            <input type="submit" value="Delete" class="btn btn-outline-primary"></input>        </form>    </div>    <div class="col"></div></div>{% endblock %}

dstargram_project/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}{% block title %}Photo Detail{% endblock %}{% block content %}<div class="col-6"> <div class="card" style="margin-top:2em;">       <div class="card-header">           {{object.author.username}}       </div>       <img src="{{object.image.url}}" class="card-img-top">        <ul class="list-group list-group-flush">            <li class="list-group-item">Like Save</li>        </ul>        {% if object.text %}       <div class="card-body">           <p class="card-text"> {{object.text}} </p>           <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>       </div>       {% endif %}       <div class="card-body">           <a href="{% url 'photo:update' object.id %}" class="card-link">수정</a>           <a href="{% url 'photo:update' object.id %}" class="card-link">삭제</a>       </div>    </div></div>{% endblock %}

dstargram_project/photo/templates/photo/photo_list.html
{% extends 'base.html' %}{% block title %}{% endblock %}{% block content %}<div class="col-6">       {% for object in object_list %}       <div class="card" style="margin-top:2em;">           <div class="card-header">               {{object.author.username}}           </div>           <img src="{{object.image.url}}" class="card-img-top">           {% if object.text %}           <div class="card-body">               <p class="card-text"> {{object.text}} </p>               <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>           </div>           {% endif %}           <ul class="list-group list-group-flush">               <li class="list-group-item">Like Save</li>           </ul>           <div class="card-body">               <a href="{{object.get_absolute_url}}" class="card-link">댓글 달기</a>           </div>       </div>       {% endfor %}   </div>{% endblock %}

dstargram_project/photo/templates/photo/photo_update.html
{% extends 'base.html' %}{% block title %}Photo Update{% endblock %}{% block content %}<div class="row">    <div class="col"></div>    <div class="col-6">        <form action="" method="post" enctype="multipart/form-data">            <div class="alert alert-info">Please enter your photo information,</div>                {% csrf_token %}                {{form.as_p}}            <input type="submit" value="Update" class="btn btn-outline-primary"></input>        </form>    </div>    <div class="col"></div></div>{% endblock %}